- better error handling for ws_share if user is not given + tests

diff --git a/bin/ws_share b/bin/ws_share
--- a/bin/ws_share
+++ b/bin/ws_share
@@ -135,6 +135,10 @@ case $ACTION in
         ;;
     share)
         USERS="$@"
+        if [[ -z "$USERS" ]]; then
+            echo "Error: No user specified"
+            exit 1
+        fi
         MACL=""
         for user in $USERS; do
             if ! id "$user" >/dev/null 2>&1; then
@@ -152,6 +156,10 @@ case $ACTION in
         ;;
     unshare)
         USERS="$@"
+        if [[ -z "$USERS" ]]; then
+            echo "Error: No user specified"
+            exit 1
+        fi
         XACL=""
         for user in $USERS; do
             if ! id "$user" >/dev/null 2>&1; then
@@ -169,6 +177,10 @@ case $ACTION in
         ;;
     sharegroup)
         GROUPARG="$@"
+        if [[ -z "$GROUPARG" ]]; then
+            echo "Error: No group specified"
+            exit 1
+        fi
         MACL=""
         for group in $GROUPARG; do
             line=$(getent group "$group")
@@ -202,6 +214,10 @@ case $ACTION in
         ;;
     unsharegroup)
         GROUPARG="$@"
+        if [[ -z "$GROUPARG" ]]; then
+            echo "Error: No group specified"
+            exit 1
+        fi
         XACL=""
         for group in $GROUPARG; do
             if ! getent group "$group" >/dev/null; then
