- added logging to ws_share

diff --git a/bin/ws_share b/bin/ws_share
--- a/bin/ws_share
+++ b/bin/ws_share
@@ -119,6 +119,13 @@ shift
 WS_NAME="$1"
 shift
 
+CALLER_USER=$(id -un)
+if [[ "$ACCESS" == "rwX" ]]; then
+    ACCESS_STR="readwrite"
+else
+    ACCESS_STR="read-only"
+fi
+
 if [[ -z "$ACTION" ]]; then
     echo "Error: no action specified"
     exit 1
@@ -158,6 +165,14 @@ case $ACTION in
             exit 0
         fi
         setfacl -R -m "${MACL%,}" "$WS_PATH"
+        if [[ $? -eq 0 ]]; then
+            for user in $USERS; do
+                logger -t ws_share -p user.info "Granted $ACCESS_STR access to user <$user> for workspace <$WS_NAME> ($WS_PATH) by <$CALLER_USER>"
+            done
+        else
+            echo "Error: Failed to set ACLs"
+            exit 1
+        fi
         ;;
     unshare)
         USERS="$@"
@@ -179,6 +194,14 @@ case $ACTION in
             exit 0
         fi
         setfacl -R -x "${XACL%,}" "$WS_PATH"
+        if [[ $? -eq 0 ]]; then
+            for user in $USERS; do
+                logger -t ws_share -p user.info "Removed access for user <$user> from workspace <$WS_NAME> ($WS_PATH) by <$CALLER_USER>"
+            done
+        else
+            echo "Error: Failed to remove ACLs"
+            exit 1
+        fi
         ;;
     sharegroup)
         GROUPARG="$@"
@@ -215,6 +238,14 @@ case $ACTION in
 	      fi
           fi
           setfacl -R -m "${MACL%,}" "$WS_PATH"
+          if [[ $? -eq 0 ]]; then
+              for group in $GROUPARG; do
+                  logger -t ws_share -p user.info "Granted $ACCESS_STR access to group <$group> for workspace <$WS_NAME> ($WS_PATH) by <$CALLER_USER>"
+              done
+          else
+              echo "Error: Failed to set ACLs"
+              exit 1
+          fi
         fi
         ;;
     unsharegroup)
@@ -235,12 +266,28 @@ case $ACTION in
             XACL+="group:$group,"
             XACL+="default:group:$group,"
         done
-        [[ -n "$XACL" ]] && setfacl -R -x "${XACL%,}" "$WS_PATH"
+        if [[ -n "$XACL" ]]; then
+            setfacl -R -x "${XACL%,}" "$WS_PATH"
+            if [[ $? -eq 0 ]]; then
+                for group in $GROUPARG; do
+                    logger -t ws_share -p user.info "Removed access for group <$group> from workspace <$WS_NAME> ($WS_PATH) by <$CALLER_USER>"
+                done
+            else
+                echo "Error: Failed to remove ACLs"
+                exit 1
+            fi
+        fi
         ;;
     unshare-all)
         echo "Warning: will produce errors on files not owned by you"
         sleep 3;
         setfacl -R -b "$WS_PATH"
+        if [[ $? -eq 0 ]]; then
+            logger -t ws_share -p user.info "Removed all shared access from workspace <$WS_NAME> ($WS_PATH) by <$CALLER_USER>"
+        else
+            echo "Error: Failed to remove all ACLs"
+            exit 1
+        fi
         ;;
     check)
         ;;
